name: magic_english_app
description: "AI-powered English learning app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- CÁC THƯ VIỆN CŨ ---
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  provider: ^6.1.1
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.4
  intl: ^0.19.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.1.0

  # --- THÊM 2 DÒNG NÀY ĐỂ SỬA LỖI ---
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LogoMagic.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B5394"
  adaptive_icon_foreground: "assets/images/LogoMagic.png"