name: magic_english_app
description: "AI-powered English learning app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  dio: ^5.4.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Utils
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - .env  # 👈 Thêm dòng này để load file .env