// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqIecQB7J4d8SOvrQjkk4i2VvOtvBiIRA',
    appId: '1:249656848522:web:31e734ff129a005e817d73',
    messagingSenderId: '249656848522',
    projectId: 'magicenglish-5b84c',
    authDomain: 'magicenglish-5b84c.firebaseapp.com',
    storageBucket: 'magicenglish-5b84c.firebasestorage.app',
    measurementId: 'G-DMKM3NSY8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5TeT8tjLp20T4Q4jELFVWE2rzhtED39w',
    appId: '1:249656848522:android:90ace5d44865133e817d73',
    messagingSenderId: '249656848522',
    projectId: 'magicenglish-5b84c',
    storageBucket: 'magicenglish-5b84c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQl-bwQz6nsIZ2c8xT1H0sodC5AqoQWjM',
    appId: '1:249656848522:ios:6f3980de7eb86d96817d73',
    messagingSenderId: '249656848522',
    projectId: 'magicenglish-5b84c',
    storageBucket: 'magicenglish-5b84c.firebasestorage.app',
    androidClientId: '249656848522-n9pk5l6o5rg7qqkv03gf7bhk783joefk.apps.googleusercontent.com',
    iosClientId: '249656848522-g95se3h9vv7aj6jj8jv2vt6s1gv6vr1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.magicEnglishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQl-bwQz6nsIZ2c8xT1H0sodC5AqoQWjM',
    appId: '1:249656848522:ios:6f3980de7eb86d96817d73',
    messagingSenderId: '249656848522',
    projectId: 'magicenglish-5b84c',
    storageBucket: 'magicenglish-5b84c.firebasestorage.app',
    androidClientId: '249656848522-n9pk5l6o5rg7qqkv03gf7bhk783joefk.apps.googleusercontent.com',
    iosClientId: '249656848522-g95se3h9vv7aj6jj8jv2vt6s1gv6vr1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.magicEnglishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqIecQB7J4d8SOvrQjkk4i2VvOtvBiIRA',
    appId: '1:249656848522:web:17e1bc18f1e21e59817d73',
    messagingSenderId: '249656848522',
    projectId: 'magicenglish-5b84c',
    authDomain: 'magicenglish-5b84c.firebaseapp.com',
    storageBucket: 'magicenglish-5b84c.firebasestorage.app',
    measurementId: 'G-LJS7BQCKWQ',
  );
}
